import { Inter } from "next/font/google";
import "./globals.css";
import AuthSessionProvider from "@/components/HOC/AuthSessionProvider";
import RecoilProvider from "@/components/HOC/RecoilProvider";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ReactQueryProvider from "@/components/HOC/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} bg-gray-200 dark:bg-gray-900 scrollbar-none md:scrollbar-thin scrollbar-thumb-primary scrollbar-track-gray-100`}
      >
        <AuthSessionProvider>
          <RecoilProvider>
            <ReactQueryProvider>
              <Header />
              <div className='bg-white dark:bg-gray-800'>{children}</div>
              <Footer />
              <div id='modal'></div>
            </ReactQueryProvider>
          </RecoilProvider>
        </AuthSessionProvider>
      </body>
    </html>
  );
}
