name: Build and Run Docker Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add Application.Properties
      run: echo "${{ secrets.PROPERTIES }}" > ./src/main/resources/application.properties
      
    - name: Clean Docker
      run: |
        chmod +x ./clean-docker.sh && bash ./clean-docker.sh

    - name: Build Docker image
      run: sudo docker build -t myapp .

    - name: Run Docker container
      run: sudo docker run -d -p 80:8080  myapp
      
