name: Build and Run Docker Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add Application.Properties
      run: echo "${{ secrets.PROPERTIES }}" > ./src/main/resources/application.properties
      
    - name: Stop Docker containers
      run: |
        ids=$(docker ps -a -q)
        for id in $ids
        do
          echo "Stopping and removing container: $id"
          sudo docker stop $id
          sudo docker rm $id
        done
      continue-on-error: true

    - name: Remove Docker image
      run: sudo docker rmi myapp
      continue-on-error: true


    - name: Build Docker image
      run: sudo docker build -t myapp .

    - name: Run Docker container
      run: sudo docker run -d -p 80:8080  myapp
      
